server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: ZmFrZS1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9uLXBsZWFzZS0xMjM0NTY=
    expiration-ms: 86400000
